Name: GBDX workflow system
Description: The GBDX batch compute engine
source: https://github.com/tdg-platform/workflows
poc_email: nricklin@digitalglobe.com
team: GBDX Core
documentation:
  - external: https://gbdxdocs.digitalglobe.com/docs/workflow-api-course
  - internal: https://link/to/internal/documentation

related components: 
  - name: gbdx worker agent
    source: https://github.com/tdg-platform/workers_and_deciders
  - name: another component
    source: https://github.com/some_other_repo

service_urls:
  - production: https://geobigdata.io/workflows/v1
  - staging: https://staging.geobigdata.io/workflows/v1
  - dev: https://auto-deploy.geobigdata.io/workflows/v1
