authentication:
  scopes:
    - abc.read
    - defg.write
    - something.dataaccess
database:
  name: petstoredb
  type: postgres
s3:
  bucket: petstore-data
itar: false
deployment_instructions:
  deploy_to_production: true
  instances:
    development: 1
    test: 2
    production: 5
