security_controls:
  - none
  
unit_test_runner: "test/unit_tests"
functional_test_runner: "test/functional_tests"
integration_test_runner:
  - "test/integration_tests"
  - "other_place"

hold_at_environment: reg

instance_specifics:
  - envs:
      - default
    min_instances: 2
    max_instances: 2
    memory: 1024M
    timeout: 60
  - envs:
      - prod
      - prod-us-east-1
      - prod-us-gov-west-1
      - reg
    min_instances: 2
    max_instances: 5
    memory: 1024M
    timeout: 60
  - envs:
      - devint-us-east-1
    min_instances: 4
    max_instances: 5
    memory: 1024M
    timeout: 60

deploy_region_opt_out:
  - dg-north-01

functional_test_region_opt_out:
  - us-east-01
  - dg-north-01
  
integration_test_region_opt_out:
  - us-east-01

up_integration_testing:
  - test_owner: image-metadata
    test_annotations:
      - my_service_name
      - all_services
  - test_owner: sips-message-producer