authentication:
  scopes:
    - mps.read
    - mps.write
    - mps.admin
database:
  name: myservicedb
s3:
  bucket: bucket-name-to-have-access-to
itar: false
deployment_instructions:
  deploy_to_production: true
  instances:
    development: 1
    test: 2
    production: 5
